---
arch: 'mobilenet_v2'
batch_size: 128
num_epoch: 150
dataset: 'imagenet'
num_classes: 1000
crop_size: 224
crop_interpolation: 2 ### 2: BILINEAR, 3:CUBIC
use_cosine_lr: True
cosine_lr_min: 0.0
warmup_epochs: 5
lr: 0.05
lr_scale_factor: 256
lr_milestones: [30, 60, 90, 100]
momentum: 0.9
wd: 0.00004
nesterov: False
activation_mode: 0 ### 1: leakyReLU, 2: , other: ReLU
#norm_name: 'BatchNorm2d'
norm_name: 'MixtureBatchNorm2d'
norm_groups: 32
norm_k: [5, 5, 5, 5, 10, 10, 10]
norm_attention_mode: 2
dataaug:
    imagenet_extra_aug: False ###ColorJitter and PCA
    labelsmoothing_rate: 0.0
    mixup_rate: 0.0
mobilenet:
    rm_se: False
    use_mn_in_se: False
